---
kind: Service
apiVersion: v1
metadata:
  name: springboot-service
spec:
  selector:
    app: springbootapp
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 8081
      # Port to forward to inside the pod
      targetPort: 8080
      # Port accessible outside cluster
      nodePort: 30002
  type: LoadBalancer



---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: springboot-deployment
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: springbootapp
    spec:
      containers:
        - name: springbootapp
          image: nuttyoctopus/kubernetes_spring-boot
          ports:
            - containerPort: 8080
